export const CHOOSE_REGION = "CHOOSE_REGION";
export const SHOW_ONE_TIME_EVENTS = "SHOW_ONE_TIME_EVENTS"
export const SHOW_STATIONARY_POINTS = "SHOW_STATIONARY_POINTS"
export const SEARCH_VALUE = "SEARCH_VALUE"
